export const trails = {
              'Barr Lake Perimeter Trail': { ascent: 35,
                                             descent: -38,
                                             difficulty: 'greenBlue',
                                             high: 5098,
                                             id: 7015169,
                                             imgMedium: 'https://cdn-files.apstatic.com/hike/7012604_medium_1456870089.jpg',
                                             imgSmall: 'https://cdn-files.apstatic.com/hike/7012604_small_1456870089.jpg',
                                             imgSmallMed: 'https://cdn-files.apstatic.com/hike/7012604_smallMed_1456870089.jpg',
                                             imgSqSmall: 'https://cdn-files.apstatic.com/hike/7012604_sqsmall_1456870089.jpg',
                                             latitude: 39.9379,
                                             length: 8.9,
                                             location: 'Lochbuie, Colorado',
                                             longitude: -104.7525, low: 5105,
                                             name: 'Barr Lake Perimeter Trail',
                                             starVotes: 2,
                                             stars: 3,
                                             summary: 'An 8+ mile trail around Barr Lake, which is easy on a bike, but long and flat on foot.',
                                             type: 'Trail',
                                             url: 'https://www.hikingproject.com/trail/7015169/barr-lake-perimeter-trail' },
              'Barr Lake Rookery': {         ascent: 35,
                                             descent: -35,
                                             difficulty: 'green',
                                             high: 5098,
                                             id: 7015153,
                                             imgMedium: 'https://cdn-files.apstatic.com/hike/7012604_medium_1456870089.jpg',
                                             imgSmall: 'https://cdn-files.apstatic.com/hike/7012604_small_1456870089.jpg',
                                             imgSmallMed: 'https://cdn-files.apstatic.com/hike/7012604_smallMed_1456870089.jpg',
                                             imgSqSmall: 'https://cdn-files.apstatic.com/hike/7012604_sqsmall_1456870089.jpg',
                                             latitude: 39.9387,
                                             length: 6.7,
                                             location: 'Lochbuie, Colorado',
                                             longitude: -104.7518,
                                             low: 5105,
                                             name: 'Barr Lake Rookery',
                                             starVotes: 1,
                                             stars: 3,
                                             summary: 'An awesome route for appreciating nature & birdwatching. Good sunrise/set views of the Front Range.',
                                             type: 'Featured Hike',
                                             url: 'https://www.hikingproject.com/trail/7015153/barr-lake-rookery' },
              'Boardwalk to Gazebo': {       ascent: 0,
                                             descent: -2,
                                             difficulty: 'green',
                                             high: 5098,
                                             id: 7015213,
                                             imgMedium: 'https://cdn-files.apstatic.com/hike/7012604_medium_1456870089.jpg',
                                             imgSmall: 'https://cdn-files.apstatic.com/hike/7012604_small_1456870089.jpg',
                                             imgSmallMed: 'https://cdn-files.apstatic.com/hike/7012604_smallMed_1456870089.jpg',
                                             imgSqSmall: 'https://cdn-files.apstatic.com/hike/7012604_sqsmall_1456870089.jpg',
                                             latitude: 39.931,
                                             length: 0.2,
                                             location: 'Brighton, Colorado',
                                             longitude: -104.7688,
                                             low: 5099,
                                             name: 'Boardwalk to Gazebo',
                                             starVotes: 0,
                                             stars: 0,
                                             summary: '',
                                             type: 'Connector',
                                             url: 'https://www.hikingproject.com/trail/7015213/boardwalk-to-gazebo' },
              'Fox Meadow Trail': {          ascent: 2,
                                             descent: -2,
                                             difficulty: 'green',
                                             high: 5099,
                                             id: 7015155,
                                             imgMedium: '',
                                             imgSmall: '',
                                             imgSmallMed: '',
                                             imgSqSmall: '',
                                             latitude: 39.9316,
                                             length: 0.3,
                                             location: 'Brighton, Colorado',
                                             longitude: -104.7622,
                                             low: 5101,
                                             name: 'Fox Meadow Trail',
                                             starVotes: 0,
                                             stars: 0,
                                             summary: '',
                                             type: 'Connector',
                                             url: 'https://www.hikingproject.com/trail/7015155/fox-meadow-trail' },
                'Inlet Gazebo Trail': {      ascent: 0,
                                             descent: -2,
                                             difficulty: 'green',
                                             high: 5098,
                                             id: 7015162,
                                             imgMedium: 'https://cdn-files.apstatic.com/hike/7012606_medium_1456870360.jpg',
                                             imgSmall: 'https://cdn-files.apstatic.com/hike/7012606_small_1456870360.jpg',
                                             imgSmallMed: 'https://cdn-files.apstatic.com/hike/7012606_smallMed_1456870360.jpg',
                                             imgSqSmall: 'https://cdn-files.apstatic.com/hike/7012606_sqsmall_1456870360.jpg',
                                             latitude: 39.9269,
                                             length: 0.2,
                                             location: 'Brighton, Colorado',
                                             longitude: -104.7801,
                                             low: 5100, name: 'Inlet Gazebo Trail',
                                             starVotes: 0,
                                             stars: 0,
                                             summary: '',
                                             type: 'Connector', url: 'https://www.hikingproject.com/trail/7015162/inlet-gazebo-trail' },
}

export const conditions = {
  conditionColor: 'Green',
  conditionDate: '2017-05-24 06:48:59',
  conditionDetails: 'Dry',
  conditionImg: 'https://cdn.apstatic.com/img/conditions/green.svg',
  conditionStatus: 'All Clear',
  id: 7008385,
  name: 'Highline Canal Trail',
  url: 'https://www.hikingproject.com/trail/7008385/highline-canal-trail',
  urlConditionsHistory: 'https://www.hikingproject.com/trail/7008385/highline-canal-trail?modal=trail-conditions-modal',
  urlConditionsUpdate: 'https://www.hikingproject.com/trail/7008385/highline-canal-trail?action=update-conditions'
}
